developit/microbundle

- README.md
> Small docs correction ✨

- package.json
- src/index.js
Adds postcss rollup plugin and autoprefixer to allow importing css files
> Add postcss and autoprefixer

- README.md
This uses the output of `microbundle --help` from version `0.4.3`
> Update the `All CLI Options` in the readme

- package.json
- src/index.js
- test/__snapshots__/index.test.js.snap
- test/fixtures/ts-demo/src/car.ts
- test/fixtures/ts-demo/tsconfig.json
- test/index.test.js
> Switch to `rollup-plugin-typescript2`

- README.md
- src/prog.js
> Support --watch flag

- package.json
Reverts developit/microbundle#145
> Revert "Update rollup to the latest version 🚀"

- .npmrc
- package.json
- src/index.js
closes #146
Still have to figure out what's going with .ts/.tsx tests, because they are failing - but I'v fixed rest of them for now.
> Updated rollup to 0.60.1, made code changes to support it

- package.json
> Remove unused regenerator-runtime dependency

- src/index.js
- test/__snapshots__/index.test.js.snap
Tis the standard and everything is converging on it, time to adopt!
> Use .mjs extension for module main output

- .gitignore
- package.json
- src/index.js
- test/__snapshots__/index.test.js.snap
Adds brotli size for each resource.
Code is not in a friendly state, but wanted to share early.
> Brotli sizes

- README.md
- src/index.js
- src/prog.js
Add --globals config in the cli that allows to rename globals dependencies.
Fixes #184
> Supports --globals config

- package.json
Combines duplicate `jest` field in `package.json`.
> Support TypeScript 3 (closes #191)

- package.json
- src/index.js
> chore: update dependencies

- src/index.js
The PR fixes the linting error and makes the CI pass again.
> Fix linting error

- test/__snapshots__/index.test.js.snap
- test/fixtures/ts-mixed-exports/package.json
- test/fixtures/ts-mixed-exports/src/car.ts
- test/fixtures/ts-mixed-exports/src/index.ts
- test/fixtures/ts-mixed-exports/tsconfig.json
- test/index.test.js
This failed trying to import `index.ts.js` before
> Add a test for mixed exports in ts

- src/index.js
- src/prog.js
Same as Terser's `--define`:
```
microbundle --define NODE_ENV=production
```
> Add define option

- .travis.yml
- package.json
- sizereport.config.js
`travis-size-report` so we can have a nice diff on each PR to see how we are doing.
> chore: add travis-size-report

- test/__snapshots__/index.test.js.snap
- test/fixtures/basic-compress-false/package.json
- test/fixtures/modern/package.json
Some tests had duplicate package names. I updated those packages and relevant snapshots to have unique names
> Fix duplicate package name warning

- src/index.js
- test/__snapshots__/index.test.js.snap
> Switch from .mjs to .esm.js to avoid webpack tomfoolery

- src/index.js
See https://github.com/terser/terser#output-options
and https://github.com/nolanlawson/optimize-js#why
> Disable Terser eager parsing hack

- package-lock.json
- package.json
- src/lib/babel-custom.js
- test/__snapshots__/index.test.js.snap
`preset-env` is currently in a state where modern isn't correctly eliminating certain polyfills
Link: https://github.com/JoviDeCroock/hooked-form/issues/84
> Implement preset-modules for modern

- README.md
- src/prog.js
> Document iife format

- README.md
> Clarify modern mode in the readme

- src/index.js
- test/__snapshots__/index.test.js.snap
- test/fixtures/ts-declaration/package.json
- test/fixtures/ts-declaration/src/index.tsx
- test/fixtures/ts-declaration/tsconfig.json
- test/fixtures/ts-declaration/types/index.d.ts
- test/index.test.js
- Fixes TS trying to include generated files
- Fixes TS declaration files emitted at wrong destination.
Fixes #621
> Fix TypeScript emit target

- src/lib/babel-custom.js
> --no-compress should preserve comments

- src/index.js
- src/utils.js
> Improve checkJs Typings

- .changeset/two-bikes-brush.md
- index.d.ts
- test/__snapshots__/index.test.js.snap
> Add ambient typescript declaration for CSS Modules

- src/index.js
> fix(cli): corrects the --sourcemap=false option parsing

- src/index.js
> Fix: throw  a warning when no entrypoint is found

- .changeset/gorgeous-singers-invite.md
- src/index.js
> Fix mangle.json being overwritten with [object Object]

- .changeset/clean-shoes-applaud.md
- src/index.js
fix NPE occured when typescript plugin goes to wrong
#934
> feat: [auto-commit] fix: _sizeInfo npe
