package.json, src/index.js
https://github.com/developit/microbundle/issues/5
=> feat: add rollup-plugin-flow

README.md
Looks like it moved to GitHub. :)
=> Update Bublé repository link in README

README.md, src/cli.js
- Adds a `name` option to the CLI, which accepts a string.
- Briefly discusses options for specifying UMB export names in the README
When bundling UMD build, it is often useful to control the export name. For instance, microbundle defaults to a snake_case version of the `name` field in `package.json`, but camelCase is generally preferred in JavaScript. Trying do so myself, I noticed [the line that determines the name](https://github.com/developit/microbundle/blob/11ee0699fa013d81802322d84c645bf9acd02ef5/src/index.js#L229) feeds from two additional sources:
- `options.name` which seems like it comes from the CLI options, but no such options exists
- `pkg.amdName` which is not a standard field AFAIK or mentioned in the README
This PR intends to fix both those things. 🙂
_It's worth noting …
=> Clarify how to specify UMD export name

appveyor.yml, package.json, src/index.js
Glob is not supported on Windows by default. So I added `glob` package. Also I added Windows CI (using AppVeyor).
AppVeyor result: https://ci.appveyor.com/project/g-plane/microbundle/build/1.0.1
Fix #20
=> Add Windows support

src/index.js
By changing "modulesOnly" to just "modules", rollup will look for an mjs module by default, but accept and bundle cjs if not. Closes #17
=> Change node resolve param to allow cjs modules, prefer mjs

package.json, src/index.js
This changes the default UMD export name from snake_case to PascalCase, per [this comment](https://github.com/developit/microbundle/pull/10#issuecomment-351415227) from another related PR. 🙂
=> Change default name from snake_case to PascalCase

src/index.js
While testing lit-html, I ran into this issue. Sounds like we want to support this.
more info here: https://buble.surge.sh/guide/#dangerous-transforms
=> Adding support for tag template strings

src/index.js
I think this fixes https://github.com/developit/microbundle/issues/28
I ran into this on a project and when it inline anything in "depedencies" will still excluding those in "peerDependencies"
=> Include dependencies

package.json, src/cli.js, src/index.js
Some of the "silent" aliases aren't included yet. They aren't documented in the README or in the CLI itself, so I think this may be a good time to address that?
These are the missing aliases:
* `d` --> `output`
* `entries` --> `entry`
* `e` --> `entry`
If these are really intended, `sade@1.1.0` is able to support that need.
I can also move some of the default values from the `index.js` into the CLI directly. For example, passing down `pkg.module` directly, since it's already there... up to you~!
=> Migrate CLI to Sade

README.md, src/cli.js, src/index.js
When building isomorphic libraries, it's useful to bundle browser versions of dependencies. The `target` option makes this possible and provides flexibility to make environment-based decisions in the future.
=> Add target environment option

src/lib/flow-plugin.js
Builds started working again fine after this.
Closes #64.
=> Guard against flow transform response

src/index.js
Add the option to emit build events when running microbundle programmatically. This is a feature I'd like to have to notify a connected browser of a change or any build errors that may have occurred.
=> Emit bundle events

package.json
https://github.com/oligot/rollup-plugin-nodent/pull/6 was merged, so the fork is not needed anymore.
=> Use upstream rollup-plugin-nodent

README.md, src/cli.js, src/index.js, test/index.test.js
I was missing this option, and I noticed @lukeed created a issue for it here https://github.com/developit/microbundle/issues/73 and you know, I had a few free minutes and why not, lend a hand. 😄 
Let me know if this is out of scope, or not really something you'd like to go towards.
=> Added source-map option

README.md
It took me a while to figure out how to specify output builds and I think it could be in a README.md
I found out that it is mentioned in #91 so I've made a PR so it's easier to find.
=> Update README.md - specify output builds in package.json

src/index.js, test/__snapshots__/index.test.js.snap, test/fixtures/basic-ts/tsconfig.json, test/fixtures/basic-tsx/package.json, test/fixtures/basic-tsx/src/index.tsx, test/fixtures/basic-tsx/tsconfig.json
- Adds `.tsx` support to microbundle and a test
- Fixes failed snapshot of `basic-lib-ts` output by declaring a proper `compilerOptions.rootDir` in `tsconfig.json`. This ensures that TS does on copies the content of the `src` folder into `dist` and not the folder itself.
=> Close #80. Add .tsx support

src/cli.js
Replaces the not-so-useful `[object Object]` error output
```
❯ yarn dev
yarn run v1.6.0
$ microbundle watch
Watching source, compiling to dist:
[object Object]
✨  Done in 1.85s.
```
... with the actual error string when available:
```
❯ yarn dev
yarn run v1.6.0
$ microbundle watch
Watching source, compiling to dist:
SyntaxError: Unexpected token (1:7) /Users/jess/dev/cete/landing-page/components/src/index.js (nodent)
export FukolGrid, { FukolItem } from './fukol-grid';
-------^
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
---
The `yarn dev` command maps to: `microbundle watch`
=> Better output when building fails on CLI

package.json, src/index.js, test/__snapshots__/index.test.js.snap, test/fixtures/basic-css/package.json, test/fixtures/basic-css/src/index.js, test/fixtures/basic-css/src/two.css
As the name of this PR suggests, this change will minify the CSS assets generated by Microbundle when the "compress" option is true. 
I'm using [cssnano](https://github.com/ben-eb/cssnano) to preform the minification using it's default "safe" mode. This also happens to be the same minifier that Webpack's "css-loader" uses.
=> Minify CSS assets with cssnano if compress option is true

src/cli.js, src/index.js, src/utils.js
First of all: __this is just a suggestion__, so feel free to close the PR if you are not interested 😸
This PR handles Rollup errors in a more graceful way (the change copies essential parts of [`rollup/bin/src/logging.ts`](https://github.com/rollup/rollup/blob/master/bin/src/logging.ts), unfortunately, Rollup doesn't export this part of the module to the public). Everything that could help users of the `microbundle` understand the underlying issue with the build is printed to the console.
This is how it looks for the failed build with this change:
I also switched microbundle from using `process.std(out|err).write` directly to using `console.(log|error)` methods. Console methods are doing the same thing, only the newlines are added automatically by console methods, so you don't need to do …
=> More helpful rollup errors

.eslintrc, lint-staged.config.js, package.json
Alternatively we can use `prettier-eslint` - this would run eslint with `--fix` right after the `prettier`
=> Turn off eslint rules inconsistent with prettier settings

src/cli.js, src/index.js, src/log-error.js
This PR applies the following:
- Fix #111 
- Ensure that errors during `watch` mode are logged in full, rather than logging `[object Object]` in terminal
- Ensure that fatal errors still trigger build failure, but other error codes should not stop the watch mode
- Pull the logging logic out of `cli.js` into `log-error.js` so that it can be used in `cli.js` and `index.js`
=> Fix #111 and log errors during watch mode

README.md
I'm a huge fan of microbundle and am using it for [react-recomponent](https://github.com/philipp-spiess/react-recomponent) as well. I would be honored to get it mentioned in the README 😊
=> Add react-recomponent to "Built with Microbundle"

package.json
Fixes jest tests failing in master because of the minor version bump in default `jsdom` environment. Root cause of the issue is described in following two issues:
- https://github.com/facebook/jest/issues/6766
- https://github.com/jsdom/jsdom/issues/2304
For `microbundle` it doesn't make sense to run tests in jsdom environment in general, so this PR fixes the issue by setting jest test environment to `node`
=> Switch jest test environment to node

README.md, package.json, src/index.js, src/prog.js
Seems there is no document for `--jsx` flag. And it's needed for build react component.
=> add the --jsx document

src/index.js
Solves #169.
Change event triggers multiple concurrent rebuilds. Error happens when multiple ts instances try to access cache files.
=> fix(typescript): add cache folder for each build format

README.md
`microbundle` generates `.mjs` files by default, this should be reflected in the readme.
=> Change "module" field from .m.js to .mjs

src/index.js, src/prog.js
Closes  #216.
Keep in mind that this is a breaking change, since we changed name of the `sourcemap` flag. I played a bit with `sade`, we can keep `sourcemap` flag as it is and it would work with `--no-sourcemap` ( it would set `sourcemap` to false ), but I think this better communicates intentions - sourcemaps are generated by default, turn them off if you want.
=> feat(sourcemaps): support for ts sourcemaps and invert sourcemap flag

babel.config.js, package.json, src/cli.js, src/index.js, test/__snapshots__/index.test.js.snap, test/fixtures/shebang/package.json, test/fixtures/shebang/src/index.js, test/index.test.js
This PR fixes a regression that was introduced with #252 . This is due to bublé not having the correct acorn options set and is made more difficult by the fact that they ship their own private acorn version.
Fixes #255 
/cc @ForsakenHarmony
=> Add back shebang handling

package.json, src/index.js, test/__snapshots__/index.test.js.snap, test/fixtures/async-iife-ts/package.json, test/fixtures/async-iife-ts/src/index.ts, test/fixtures/async-iife-ts/tsconfig.json, test/fixtures/async-ts/package.json, test/fixtures/async-ts/src/index.ts, test/fixtures/async-ts/tsconfig.json, test/fixtures/esnext-ts/src/index.ts
=> Fix async not transpiled with TS

src/index.js
=> fix: support hoisted packages

package.json, src/index.js, test/__snapshots__/index.test.js.snap, test/fixtures/default-named/package.json, test/fixtures/default-named/src/index.js, test/index.test.js
Fixes #264 
**EDIT:** PR #262 likely needs to be merged first, as that one fixes the failing CI.
=> Remove import pruning

README.md
Microbundle is JUST the bundling tool I've been looking for, thanks for this!
I would be honoured to have my library mentioned in the "Built with Microbundle" section.
repo: https://github.com/JReinhold/mdx-deck-live-code
demo: https://reinhold.is/live-coding-in-slides
=> add mdx-deck-live-code to "Built with..." section

src/index.js, src/prog.js
Same config parsing and format as `--globals` and [`--define`](https://github.com/developit/microbundle/pull/312):
```sh
microbundle --alias debug=./debug.js
```
=> Add support for --alias

src/index.js
This pull request moves the `treeshake` value that is passed to Rollup. Based on [the documentation](https://rollupjs.org/guide/en#inputoptions) it should be a part of the `inputOptions` object instead of `outputOptions`.
=> Move Rollup 'treeshake' value to be a part of inputOptions

README.md
I'm assuming you meant that Nodent?
Thanks for all your good work!
=> + Nodent link in Readme

src/index.js
This allows specifying Terser options in mangle.json or package.json. The old `"mangle"` field is still supported for legacy reasons alongside the new `"minify"` option.
```js
// in `mangle.json` or `package.json`:
{
"minify": {
// old/simple variant:
"regex": "^_",
// new: customize any terser options:
"compress": {
"hoist_vars": true,
"reduce_funcs": false
}
}
}
```
This is useful for projects that are already structured with functions aimed at gzip compression optimization.
=> Add compressor options

README.md, src/prog.js
The default for `--target` was updated to `web` in 071861e374a1a13acb9e4a4c6cb6792fc0ff10cf but the README still shows the old default (`node`). This updates the README to show the correct default.
Also specifies `node` and `web` and the possible values for target. From what I understand, `node` is really the only special value and anything other than `node` will behave the same, but I think it is nice to have some suggestions.
=> Correct default --target option

test/index.test.js
This pull request aims to fix failing tests by upping the timeout for fixture tests from 5000ms to 11000ms.
Currently the tests are failing for multiple pull requests and also for the master branch. These failures seem to be caused by the `esnext-ts` test taking longer than the default 5000ms test timeout allows. In those cases Jest fails the test and moves on to the next one. There is no cancellation mechanism, however, so the failed async test may still continue running. Effectively there are then two or more tests running concurrently within the same process, which can cause `process.chdir` calls go out of sync. See https://travis-ci.org/developit/microbundle/builds/508413269#L555 for an example.
This proposed "fix" doesn't really address the deeper causes (tests taking too long / …
=> Fix failing tests by setting fixture test timeout to 11000ms

package.json, src/index.js, test/__snapshots__/index.test.js.snap
This pull request implements the `--define` feature with [babel-plugin-transform-replace-expressions](https://github.com/jviide/babel-plugin-transform-replace-expressions) instead of using Terser. The Babel plugin is also applied to node_modules, because the transformation happens before bundling.
In the end this change allows things like using `--define DEBUG=true` for the following code and getting the expected result:
```js
const DEBUG = false;
if (DEBUG) {
console.log("DEBUG!");
}
```
Previously it seemed that in a case like this Rollup's dead code elimination did its job before Terser had the chance to replace `DEBUG`. Therefore the corresponding `console.log` statement line got always removed.
There seems to be a very slight performance impact. Without any `--define` definitions …
=> Implement --define with babel-plugin-transform-replace-expressions

src/index.js, test/__snapshots__/index.test.js.snap, test/fixtures/basic-multi-source/a.js, test/fixtures/basic-multi-source/b.js, test/fixtures/basic-multi-source/package.json
With this PR, I am to solve issue #364, however I believe this shouldn't also need to support `source` that could be either a directory, or a file, or a glob. To keep things simple.
fixes #364
=> Support package.json source array

src/index.js
The latest in-range version of [rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-node-resolve) has deprecated some options which results in several annoying warning logs every time you build with `microbundle`.
This is a very simple change that fixes these warnings.
Before:
```
yarn install v1.15.2
warning ../package.json: No license field
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ npm run -s build
node-resolve: setting options.module is deprecated, please override options.mainFields instead
node-resolve: setting options.jsnext is deprecated, please override options.mainFields instead
node-resolve: setting options.module is deprecated, please override options.mainFields instead
node-resolve: setting options.jsnext is deprecated, please override …
```
=> Fix node-resolve warnings

package.json, src/lib/babel-custom.js, test/__snapshots__/index.test.js.snap, test/fixtures/basic-babelrc/src/index.js, test/fixtures/macro/package.json, test/fixtures/macro/src/index.js, test/fixtures/macro/src/macro.js
I think it'd be very useful to support Babel macros out of the box, they allow to use Babel without additional configuration so they can improve a lot the developer experience without adding extra configuration to Microbundle.
Zero config tools such as create-react-app already support it.
=> feat: add support for Babel macros

package.json
Downgrade `core-js` so microbundle will work again
=> fix: pin core-js to 3.1.3

README.md
I was peeking into your last PR, & noticed this was odd.  A global 'repleace' error? Seems the new <command> is wrong.
Last example makes more sense as `watch`.
Thanks for adding the `modern` option! :)
=> fix Examples in README

src/index.js, test/__snapshots__/index.test.js.snap, test/fixtures/mangle-json-file/mangle.json, test/fixtures/mangle-json-file/package.json, test/fixtures/mangle-json-file/src/index.js, test/fixtures/mangle-json-file/src/two.js, test/fixtures/minify-config/package.json, test/fixtures/minify-config/src/index.js, test/fixtures/minify-config/src/two.js, test/fixtures/minify-path-config/minify.json, test/fixtures/minify-path-config/package.json, test/fixtures/minify-path-config/src/index.js, test/fixtures/minify-path-config/src/two.js, test/fixtures/minify-path-parent-dir-with-cwd/minify-path-parent-dir/index.js, test/fixtures/minify-path-parent-dir-with-cwd/minify-path-parent-dir/package.json, test/fixtures/minify-path-parent-dir-with-cwd/minify-path-parent-dir/two.js, test/fixtures/minify-path-parent-dir-with-cwd/minify.json, test/fixtures/minify-path-parent-dir-with-cwd/package.json
Some projects need to share a terser mangle-props name cache between different projects. This PR adds the ability to define a path to a shared name cache file that can be used across different projects.
It also adds some tests for the minify package.json property and mangle.json file.
=> Add support for custom mangle.json paths

README.md, src/index.js, src/prog.js
With `tsconfig.json` [extends](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#configuration-inheritance-with-extends) option, it is usually normal for a project to have multiple `tsconfig.json`s for different purposes, such as test, build, IDE IntelliSense, etc.
With this PR, a `tsconfig` option from cli can be passed down to `rollup-plugin-typescript2` when defined.
=> feat: add support for custom tsconfig path

src/index.js
Addresses #487 by catching any error for `brotliSize` and not displaying stats for brotli.
=> wrap brotli in try/catch to avoid error for lower versions of node

src/index.js
- Support import JSX from JS file by adding JSX extension to `@rollup/plugin-node-resolve` plugin 
I have experience an error when importing `.jsx file` from `.js` file like
```
index.js -> A.jsx
```
will cause an error  
```
Could not resolve './A' from src/index.js
```
However, Importing `.jsx` file from TypeScript file (`.ts`) file is seems working fine except the the import is chaining more than 3 levels depth. 
```sh
index.ts -> A.jsx # This is fine
index.ts -> A.jsx  -> B.jsx # This is fine
index.ts -> A.jsx  -> B.jsx -> C.jsx 
```
To reproduce the issue
```sh
git clone -b import-jsx-error --single-branch git@github.com:n3tr/microbundle-example.git
cd microbundle-example
yarn
yarn build --jsx React.createElement ./src/index.js 
yarn build --jsx React.createElement ./src/index.ts
``` …
=> Support import JSX from JS file

src/index.js
This option was enabled by default at some point in the node-resolve plugin, which should already have fixed #303 and #288. It still prints a warning though, which is illogical when we're compiling for a Node target. This silences that warning.
=> Set preferBuiltins:true for Node

src/index.js
I don't know why I had this as undefined. We never want to inline built-ins.
=> preferBuiltins: true for node, false for web

src/index.js, test/__snapshots__/index.test.js.snap
This actually fixes the problem that was causing modern output to often be transpiled to ES5 like the ESM output. Rollup caches transforms, so we have to disable that caching when performing the modern build. This avoids "bleeding" Babel transformations/config between modern and legacy builds (in either direction).
I believe this was the last thing left to do before we agreed on a 0.12 official release.
=> Fix babel modern

src/lib/babel-custom.js, src/lib/transform-fast-rest.js, test/__snapshots__/index.test.js.snap
This adds a Babel transform that converts rest parameters to an inline slice. The result is that all output sizes in all tests are now smaller in 0.12 than in 0.11, which means we can finally roll over to 0.12 as the stable release.
**source code:**
```js
function sum(a, b, ...c) {
return c.reduce((t, v) => t + v, a+b);
}
```
**current output:**
```js
function sum(a, b) {
for (var r = arguments.length, c = new Array(r > 2 ? r - 2 : 0), e = 2; e < r; e++) c[e - 2] = arguments[e];
return c.reduce((r, e) => r + e, a + b);
}
```
**update with this PR:**
```js
function sum(a, b) {
return [].slice.call(arguments, 2).reduce((t, v) => t + v, a + b);
}
```
=> Fast rest parameters

src/index.js, test/__snapshots__/index.test.js.snap, test/fixtures/ts-jsx/package.json, test/fixtures/ts-jsx/src/index.tsx, test/fixtures/ts-jsx/tsconfig.json
TypeScript is unable to resolve Fragments when the `jsxFactory` option is set. This is a [known issue](https://github.com/microsoft/TypeScript/issues/20469#issuecomment-631580333) for years at the TypeScript project. But the problem is that it will still break, even when you set it to the default value :shrug: 
Fixes #622
=> TS: Fix Fragments broken when jsxFactory is set

package-lock.json, package.json, src/lib/babel-custom.js
This allows the use of `import.meta`, which is supported by Rollup but needs a plugin in order to be passed successfully through Babel.
=> Allow import.meta

README.md
Just a small clarification that the externals default is `peerDependencies` and `dependencies`.
(Not sure if this is *needed* as obviously this is a sensible default, but it wasn't clear until checking the code that we didn't need to have `external`s that mirrored `peerDependencies` like you might if setting up rollup from scratch)
https://github.com/developit/microbundle/blob/ded90ace965eabdf1707d1a75b20629513086775/src/index.js#L406
=> Update option docs for --externals (default peerDependencies & dependencies)

src/index.js, test/__snapshots__/index.test.js.snap, test/fixtures/ts-module/package.json, test/fixtures/ts-module/src/foo.ts, test/fixtures/ts-module/src/index.ts, test/fixtures/ts-module/tsconfig.json
TypeScript builds must always have the esm format, otherwise bundling fails. Due to testing setups (mocha/jasmine/...) users may have explicitly declared the module type to be `CommonJS` in `tsconfig.json`. This breaks `microbundle`.
To fix this we can silently overwrite the specified module type to the one we need and let TS take care of the rest.
=> Fix TS failing if module is set to CommonJS

tools/build-fixture.js
- Clear generated type folder before running each test
~~Just cleared my `node_modules` and reinstalled them. From the looks of it the newer dependencies than what I had locally lead to some snapshot changes.~~
(_Turns out that this was caused by a different node version_)
=> Clear generated types before test run

src/index.js
This includes the change regarding: https://github.com/developit/microbundle/issues/643#issuecomment-636536332
I tested it with `npm link` on my https://github.com/katywings/microbundle-test repository.
=> fix: set types declarationDir based on cwd (#643)

README.md, src/index.js, src/prog.js, test/__snapshots__/index.test.js.snap, test/fixtures/basic-no-pkg-main/package.json, test/fixtures/basic-no-pkg-main/src/index.js, test/fixtures/basic-no-pkg-main/src/two.js
The goal of this feature is to add a solution for microbundle, to manually disable the package.json / format suffix automations analog to https://twitter.com/Katy_Wings/status/1271189844077748224
The new option `--pkg-main` by default is true - basically notifying the consumer that main entries in package.json will be considered. The consumer can supply `--pkg-main false` to disable the microbundle package.json "sideffects".
This PR also includes a little refactor of the "main" generation - most of it is the same as before but just moved into separate functions.
=> feat: add --pkg-main option

package-lock.json, package.json, src/index.js
During some investigation in the rollup external test logic I noticed, that the external parts are joined into a regex without any escaping. 
Background:
Originally I thought this was the reason for some problems with bundling "lodash.isPlainObject" (notice the dot) but that actually has some other cause... Still I think that adding the regex escaping might be wise here. Let me know what you think ;).
=> fix: escape rollup external test items

src/lib/babel-custom.js
Here's the difference:
This uses the copy of `@babel/core` that is being used to transform and run plugins:
```js
export function custom(core) {
return {
config() {
core.createConfigItem(...)
}
}
}
```
This uses the copy of `@babel/core` that npm installed for Microbundle, which may be different:
```js
import core from '@babel/core';
export function custom() {
return {
config() {
core.createConfigItem(...)
}
}
}
```
Fixes #657.
=> Use DI to prevent multiple copies of @babel/core

src/index.js
This is an addendum to #650. It escapes externals that are generated from package.json or static lists, while still allowing regular expression `--externals` values from the command line argument.
/cc @katywings @krobing
=> Allow RegExp --externals only for the CLI argument

src/index.js, test/__snapshots__/index.test.js.snap, test/fixtures/basic-dashed-external/package.json, test/fixtures/basic-dashed-external/src/index.js, test/fixtures/basic-dashed-external/src/two.js
I should go vacuum-cleaning now, but here is the short description:
Currently microbundle adds externals to globals - excluding externals with dash (`-`). This results in rollup detecting the missing explicit global and defining the global implicitly with the name camel cased. Also will rollup log a warning like: `No name was provided for external module 'microbundle-test' in output.globals – guessing 'microbundleTest`.
Since microbundle is adding the externals to globals by default, it should also include those with a dash as mentioned [here](https://github.com/developit/microbundle/issues/643#issuecomment-641071232) - and therefore avoid the `No name was provided` rollup warning. Since rollup handles its dash fallback by adding the external camel cased to globals, microbundle should …
=> fix: add externals with dash to globals (#643)

src/index.js, test/__snapshots__/index.test.js.snap, test/fixtures/alias-external/package.json, test/fixtures/alias-external/src/colossal-glob.js, test/fixtures/alias-external/src/index.js
A module cannot be an alias and a external at the same time - rollup just ignores those aliases and keeps them as is.
IS: As example: if a module `X` is declared as external, the alias `X=Y` will not work, the bundle will just keep use `X`.
SHOULD: The alias `X=Y` should work even if `X` is declared as external.
=> fix: dont set aliases as externals

src/cli.js, src/index.js, tools/build-fixture.js
Copied from the commit description ;)
- Adds onStart and onError microbundle js options:
onStart: is called when rollup noticed file changes and is starting with
bundling
onError: called if the rollup watcher is emitting any bundle errors
- Changes microbundle return type to:
```ts
{
output?: string,
watchers?: {
"inputFileName": RollupWatcher
}
}
```
- Removes obsolete rollup watch FATAL event handling
=> Add onStart and onError callbacks, accessible rollup watchers

src/index.js
Refactoring the rollup output options to use a combination of `dir` and `entryFileNames`. Afaik this should not have any negative effects regarding the microbundle output whatsoever. But it enables dynamic import rollup support - as long as the consumer only uses output formats except of `umd` and `iife` :partying_face:
=> refactor: use rollup dir and entryFileNames options instead of file

README.md
This MR adds an explainer to the settings you should set in tsconfig.json lest you run into type errors.
See #675
=> Add TypeScript target and module settings explainer

src/cli.js, src/index.js, src/lib/compressed-size.js, src/lib/css-modules.js, src/lib/option-normalization.js, src/lib/package-info.js, src/lib/terser.js, src/log-error.js, src/prog.js, src/utils.js
Extracted multiple utilities out of the main isFile
/utils.js
- isDir
- isFile
- stdout
- stderr
- isTruthy
- removeScope
/lib/compressed-size.js
- getSizeInfo
/lib/terser.js
- normalizeMinifyOptions
/lib-option-normalization.js
-	parseAliasArgument,
- parseMappingArgument
- toReplacementExpression
/lib/package-info
- getConfigFromPkgJson
- getName
/lib/css-modules
- shouldCssModules
- cssModulesConfig
=> refactor: split utilities in separate files

README.md
Closes #673 
It's not possible to actually specify where to place the declarations file. This PR attempts to clarify the README.
=> Clarify typescript declarations directory doc

README.md
unless I am mistaken the default export name for the module is in camelCase not snake_case
=> [DOC] umd module default name is in camelCase not snake_case

.changeset/tame-singers-grin.md, package.json, src/index.js, test/__snapshots__/index.test.js.snap, test/fixtures/basic-node-internals/package.json, test/fixtures/basic-node-internals/src/index.js
Disables warnings for node's builtin modules like stream, child_process when target is node. Rollup-node-resolve marks these modules as external but still shows a warning.
```
console.warn node_modules/rollup/dist/shared/node-entry.js:13595  
'child_process' is imported by src\index.js, but could not be resolved – treating it as an external dependency
```
=> fix: disable node-builtin warnings

.changeset/tall-paws-end.md, src/index.js
It seems like we're missing the `unpkg` alias for `umd:main` that's defined in our README.md file. I've added it again.
Fixes https://github.com/developit/microbundle/issues/642
=> chore: enable unpkg alias again

.changeset/chilled-paws-confess.md, src/index.js
Using a prefixed name like `{ "amdName": "global.foo" }` will trigger Rollup's `output.extend` option. This addresses the use-case from #709 without adding another CLI flag.
=> Support global extend via amdName

src/lib/babel-custom.js
@developit added @babel/env check again to microbundle. Npm doesn't have the package https://www.npmjs.com/package/@babel/env. It's the reason why I removed it so unsure what alias is meant in https://github.com/developit/microbundle/pull/702#discussion_r479397230. I'll change the comment in this PR to be more descriptive when I get more info.
Got removed in https://github.com/developit/microbundle/pull/702#discussion_r479397230
Note: this does not need a changeset
=> fix: bring back @babel/env preset match

test/index.test.js
There is a small typo in test/index.test.js.
Should read `really` rather than `realy`.
=> docs: Fix simple typo, realy -> really

.changeset/quick-lies-buy.md, README.md, package-lock.json, package.json, src/index.js, src/lib/babel-custom.js
This is an update to support the new JSX runtime in the preact@10.5.0 release! If you don't provide the flag it'll work as normal with the default or provided JSX pragma. If it it provided and for example "preact" it'll work in the new way. 🎉
More info here: https://github.com/preactjs/preact/releases/tag/10.5.0
=> Add jsxImportSource flag for new JSX runtime

.changeset/hip-papayas-pretend.md, src/index.js, test/__snapshots__/index.test.js.snap
I [constantly get tripped up by this](https://github.com/preactjs/legacy-compat/commit/e1f78210820c9ed66259f8fd7be58def66d5f019). Without this change, Microbundle compiles `-f esm` without any errors, but it actually writes an ES Module bundle to the configured CJS output file (even if there's also `-f cjs` listed). With this change, `-f esm` is identical to `-f es`.
=> Support "esm" as an alias of "es" format

.changeset/angry-goats-knock.md, src/index.js
=> Friendly microbundle-specific resolve errors

README.md
aliasing react=preact doesn't work because the main preact package actually doesn't contain any default exports. So the more likely example would be to reference preact/compat.
=> Update examples to reference preact/compat instead of preact

README.md
In the future (maybe super soon?) we can use the package exports figure out which modules to compile and where to put the outputs.
=> Update the readme to recommend package exports

.changeset/silver-guests-brake.md, package-lock.json, package.json, src/index.js
This PR is aimed at fixing #711.
Microbundle will load "typescript" from `path.dirname(process.argv[1])`.
If no `process.argv[1]`, or failed to resolve "typescript" from there, fallback to the bundled "typescript".
P.S.
Using `resolve-from@v4.0.0` instead of the latest `v5.0.0` because `v4.0.0` has already been in `package-lock.json`.
=> Use user's typescript first, fallback to bundled

.changeset/rude-keys-eat.md, README.md, src/index.js, src/prog.js, test/__snapshots__/index.test.js.snap
=> Add --css inline option

README.md
Without this package imports fail on linux debian for some reason. ¯\_(ツ)_/¯
"SyntaxError: Cannot use import statement outside a module"
=> Add missing `./`

.changeset/cold-moose-cough.md, README.md, src/index.js, src/prog.js, test/__snapshots__/index.test.js.snap, test/fixtures/ts-custom-declaration/package.json, test/fixtures/ts-custom-declaration/src/index.js, test/fixtures/ts-custom-declaration/tsconfig.json, test/fixtures/ts-custom-declaration/types/index.d.ts, tools/build-fixture.js
=> fix: add generateTypes cli option, check false value correctly

README.md
I think having two fields in the examples is confusing, especially since I could not find recent sources recommending `esmodule` any more.
Related to https://github.com/developit/microbundle/pull/781
=> docs: use "exports" key in all examples

src/lib/transform-fast-rest.js, test/__snapshots__/index.test.js.snap, test/fixtures/parameters-rest-closure/package.json, test/fixtures/parameters-rest-closure/src/index.js
=> fix(transform-fast-rest): rest parameters references with closures

.changeset/odd-pets-type.md, README.md, src/index.js, test/__snapshots__/index.test.js.snap, test/fixtures/publish-config/package.json, test/fixtures/publish-config/src/foo.ts
=> feat: enabled config overriding by publishConfig

README.md, src/index.js
The old implementation will not allow to use a filename with the extension ".cjs" in the "main" field and does not create a Common JS file with a ".cjs" ending.
If a package.json contains "type":"module"  all files with ".js" will throw an error if they are imported with an `require` function. 
This fix:
* will strip `.cjs` when creating the base name
* switch from default extension `.js` to `.cjs` when `"type":"module"` exists in `package.json`
* update documentation to highlight the problem
This solves #801
=> fix default extension to cjs for package.json "type":"module" 

README.md, src/prog.js
Addresses the footer of https://github.com/developit/microbundle/issues/775#issuecomment-753371904
Replaces "`es`" in the output formats section of the ReadMe + CLI's help with "`esm`". The format is otherwise always referred to as "ESM" or "ES Modules" so I agree that's a fair change to make. 
Note: There's a few unrelated changes caused by the prettier pre-commit hook. I'd normally revert the unrelated changes but I figure the hook is there to be used.
=> docs: Swapping out references of ES format to ESM

.changeset/modern-students-give.md, src/index.js
Fixes #776 
A bug with #769 meant that for each JS file output format (excluding UMD) a matching CSS file would be generated, i.e., `index.modern.css` and `index.module.css` (not a CSS module).
I corrected this by [restoring the old logic used](https://github.com/developit/microbundle/commit/967f8d532785aa7bf8636c5a759759a3e72dcf56#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556L448), which was relying on `writeMeta`.
=> fix: Extra CSS files generated

.changeset/tender-pants-film.md, src/index.js
Closes #783 
Allows users to customize modern output file name with `exports` like they can with `esmodules`.
=> feat: Support customizing the modern output via "exports"

.changeset/late-bags-argue.md, src/lib/babel-custom.js, test/__snapshots__/index.test.js.snap, test/fixtures/terser-annotations/mangle.json, test/fixtures/terser-annotations/package.json, test/fixtures/terser-annotations/src/index.js
We were stripping out everything except `__PURE__`, but Terser has a number of annotations using that format - these were previously being ignored.
=> Bugfix: preserve Terser annotations during Babel pass

.changeset/rude-books-judge.md, src/index.js, src/lib/terser.js, test/__snapshots__/index.test.js.snap, test/fixtures/minify-config-boolean/package.json, test/fixtures/minify-config-boolean/src/index.js, test/fixtures/minify-config-boolean/src/two.js
**Context:** Disabling Terser's mangling completely is only possible by setting `mangle` to `false`, but currently Microbundle replaces any non-object `mangle` option by `{}`.
This PR adds a special condition to allow the minify options `compress` and `mangle` to be set as booleans.
=> Fix: Support booleans in minify options

.changeset/gold-cherries-deliver.md, src/index.js, test/__snapshots__/index.test.js.snap
Related to https://github.com/developit/microbundle/issues/871.
This PR fixes the regexp that preserves terser annotations in bundles.
=> Fix: preserve terser annotations regexp

README.md
Closes #807
When building with TypeScript, [we provide a default value for `"files"`](https://github.com/developit/microbundle/blob/b1a637486234a2ae784ccf0c512321e2d3efef7c/src/index.js#L533) which has the side effect of altering what files are included for compilation with Microbundle. While this is intentional (see #621) it isn't exactly obvious to users why files included when using `tsc` are suddenly not included when using Microbundle.
=> docs: Adding comment about file inclusion in TS section

.changeset/tame-horses-type.md, README.md, src/prog.js
Kindly brought up by https://github.com/developit/microbundle/issues/454#issuecomment-946226758
=> fix: Ensuring CLI & docs match up with each other

.changeset/light-trainers-obey.md, src/index.js, src/utils.js
=> fix: Corrects CSS output being overwritten when .cjs ext used

.changeset/odd-mayflies-clap.md, README.md, src/index.js, src/prog.js
https://github.com/developit/microbundle/issues/809#issuecomment-1025937798
I removed the `options.jsx === 'React.createElement'` thing as it's no longer relevant with `jsxFragmentFactory` (see https://github.com/developit/microbundle/pull/623#issuecomment-632442811) and we set default values in the CLI for both `jsx` and `jsxFragment`, so we don't really need extra fallback values.
=> chore: Adding flag & docs for jsxFragment

.changeset/big-cameras-attend.md, README.md, src/prog.js
Adds information on default value of `--compress` flag, as that seems to be a popular complaint at the moment.
CLI needed to switch to having an undefined value to ensure Sade didn't document the default value in addition to the default value we write in the description of the flag. Just means we have to switch the `null` check to `undefined`.
Also fixes some formatting inconsistencies for other default values.
=> docs: compress flag

.changeset/clever-chicken-end.md, src/index.js
Closes #939
Simply ensures the TS plugin will begin its search for a `tsconfig.json` in the specified `--cwd`.
This is not a breaking change; in the case of a `tsconfig.json` only existing higher in a project structure, and not in the passed `--cwd`, rpt2 (which makes use of `typescript` itself, actually) will ascend the file tree attempting to discover a config file.
=> fix: tsconfig cwd differing from microbundle's cwd

.changeset/clean-ducks-push.md, README.md, src/index.js, test/__snapshots__/index.test.js.snap
Per the conversation on Slack, both modern and esm output formats may now create `.mjs` files when appropriate.
=> refactor: Output ESM files w/ `.mjs` when appropriate

test/__snapshots__/index.test.js.snap
Didn't rebase following the visualizer being merged, so these tests need to be corrected.
=> fix: Test failures following merge

README.md, src/prog.js
See https://github.blog/changelog/2022-04-25-git-io-deprecation/.
Apologies in advance for the incoming barrage of PRs doing the exact same thing, hope you don't mind.
=> Remove git.io usages

.changeset/hot-dryers-train.md, src/index.js
The current solution for matching builtins doesn't catch imports using the new-ish `node:` protocol:
```
Failed to resolve the module node:http imported by src/index.js
Is the module installed? Note:
↳ to inline a module into your bundle, install it to "devDependencies".
↳ to depend on a module via import/require, install it to "dependencies".
```
This just adds it to the patterns to match against when the target for Microbundle is Node.
=> chore: Silence warnings when using 'node:' protocol

.changeset/breezy-cheetahs-kick.md, src/index.js
I don't think there's many, if any, situations in which this would be a problem per se, but v8 is a bit old now. Just happened to noticed unused `catch` bindings being created, rather than allowing them to be omitted in Microbundle's output ([supported since Node v10](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#browser_compatibility)). 
As v12 has only been EOL for 3 days now, I figure it might be a bit early to bump this to v14.
=> chore: Bump Node target version to v12

README.md
OMT only supports amd or esm as output, so the readme should not
mention umd as supported.
When executing microbundle with umd format and `--workers`, the web
worker will fail to be detected or bundled.
=> Remove mention of UMD support for web workers

.changeset/green-foxes-poke.md, package-lock.json, package.json
Hi 👋  , by way of introduction, I help maintain [`rollup-plugin-typescript2`](https://github.com/ezolenko/rollup-plugin-typescript2) and also formerly solo-maintained [TSDX](https://github.com/jaredpalmer/tsdx) for ~1.5 years (the creator hasn't been involved in years and his abusiveness was central to [me leaving OSS for over a year](https://twitter.com/agilgur5/status/1488621603944554496?s=20&t=rwq0kNT4T9BLBaZxJcMvVg)), so I'm very familiar with the internals of `microbundle` as well.
I was investigating https://github.com/ezolenko/rollup-plugin-typescript2/issues/295 and found that `microbundle` is on an older version of rpt2, causing several issues in this repo.
Upgrade rpt2 to [v0.32.0](https://github.com/ezolenko/rollup-plugin-typescript2/releases/0.32.0) to fix various monorepo …
=> deps: upgrade rpt2 to latest v0.32.0 to fix monorepos

.changeset/angry-worms-smell.md, src/index.js, test/__snapshots__/index.test.js.snap, test/fixtures/basic-multi-source-css/a.css, test/fixtures/basic-multi-source-css/a.js, test/fixtures/basic-multi-source-css/b.css, test/fixtures/basic-multi-source-css/b.js, test/fixtures/basic-multi-source-css/package.json
fix: css compilation problems when multiple entries
This commit fixes that when different entries reference different CSS, only the related CSS of the first entry will be packaged. For specific changes, please see this commit. I also added the corresponding test case
[Original PR](https://github.com/developit/microbundle/pull/960)
=> fix: css compilation problems when multiple entries

.changeset/old-dodos-laugh.md, src/index.js, test/__snapshots__/index.test.js.snap, test/fixtures/custom-outputs-alt/package.json, test/fixtures/custom-outputs-alt/src/index.js, test/fixtures/custom-outputs-alt/src/two.js, test/fixtures/custom-outputs/package.json, test/fixtures/custom-outputs/src/index.js, test/fixtures/custom-outputs/src/two.js
Fixes #963 
Typo was from https://github.com/developit/microbundle/pull/950
We were missing tests for controlling the output filenames from `package.json` nearly entirely, both the common fields (`"main"`, `"module"`, etc.) and their alts (`"cjs:main"`, `"esmodule"`, etc.). This adds a test suite for both (though there's still a few untested fields, like nested `"exports"` and `"syntax.esmodule"` entry).
=> fix: mains by format fallbacks

README.md
Fixes #990 by adding some examples to the README, along with more context in the TypeScript section.
=> Add example of exports.types field

.changeset/gold-berries-march.md, src/index.js
This preserves tab-style indentation in `mangle.json`.
=> Fix `mangle.json` indentation style not preserved

.changeset/swift-plums-fix.md, src/index.js
Closes #682
Re:https://github.com/developit/microbundle/issues/682#issuecomment-1221769448, the warning is silenced globally.
I'm a little apprehensive about not limiting this to `node_modules/` though, as it could warn of a legitimate issue.
=> chore: Silence Rollup's `this is undefined` warnings

README.md
No pressure if you're not looking for new listings here, but working with Microbundle has been great! 🙂
=> Add glTF Transform to "Built with Microbundle" list

README.md
I made a PR for eta js, and I discovered it was build with microbundle :)
=> chore: add eta js to readme

README.md
Found out that `brazilian-utils` [isn't using microbundle anymore ](https://github.com/search?q=repo%3Abrazilian-utils%2Fbrazilian-utils%20microbundle&type=code) 😞
=> chore: remove `brazillian-utils` from readme

README.md
This service recursively checks/lists all licenses within a package's dependency graph. I remember there being a fair number of pieces involved here so was happy to see that all 400+ licenses involved are green!
Also, hello! 👋
=> chore: add licenses badge
